@jwtToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlZDU2M2IxNy0xYTUzLTQ1ZmQtOTgzMS00ZjNiNzNlOTVjODIiLCJlbWFpbCI6IlJhbUBleGFtcGxlLmNvbSIsImFkbWluIjp0cnVlLCJpYXQiOjE3NzM3NTQ1MzIsImV4cCI6MTc3Mzg0MDkzMn0.cMETLeOevfEpwWccLxyWP2FFiIbq9uWwZn5sZxEYT6Q

### Sign in first and copy accessToken into jwtToken above
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
  "email": "Ram@example.com",
  "password": "Hellloooo123"
}

### Create Post
POST http://localhost:3000/posts
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
  "title": "My 1st post",
  "description": "This is my 1st NestJS post"
}

### Get All Posts
GET http://localhost:3000/posts

### Get Signed-in User Posts
GET http://localhost:3000/posts/me
Authorization: Bearer {{jwtToken}}

### Get One Post
GET http://localhost:3000/posts/25bfe95c-ff9a-4def-b176-c6a2d6ea874d

### Delete Post
DELETE http://localhost:3000/posts/25bfe95c-ff9a-4def-b176-c6a2d6ea874d
Authorization: Bearer {{jwtToken}}
