@jwtToken = REPLACE_WITH_JWT_TOKEN

### Sign in first and copy accessToken into jwtToken above
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
  "email": "mohna1@example.com",
  "password": "Hello123"
}

### Create Post
POST http://localhost:3000/posts
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
  "title": "My 3rd post",
  "description": "This is my 3rd NestJS post"
}

### Get All Posts
GET http://localhost:3000/posts

### Get Signed-in User Posts
GET http://localhost:3000/posts/me
Authorization: Bearer {{jwtToken}}

### Get One Post
GET http://localhost:3000/posts/dd0a9d9d-1ee7-11f1-9aef-0a002700000e

### Delete Post
DELETE http://localhost:3000/posts/dd0a9d9d-1ee7-11f1-9aef-0a002700000e
Authorization: Bearer {{jwtToken}}
