###Create a new user
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "email": "mohna1@example.com",
  "password": "Hello123",
  "name": "Mohna Dutta",
  "admin": true
}

###Get a user by id
GET http://localhost:3000/users/3

###Who am I?
GET http://localhost:3000/auth/whoami

###Sign out
POST http://localhost:3000/auth/signout

###Sign in
POST http://localhost:3000/auth/signin
Content-Type: application/json


{
  "email": "mohna1@example.com",
  "password": "Hello123"
}
