@jwtToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlZDU2M2IxNy0xYTUzLTQ1ZmQtOTgzMS00ZjNiNzNlOTVjODIiLCJlbWFpbCI6IlJhbUBleGFtcGxlLmNvbSIsImFkbWluIjp0cnVlLCJpYXQiOjE3NzM3NTQ0MDMsImV4cCI6MTc3Mzg0MDgwM30.h8r4uzbIzMXpjB4Y52oKZwnGVykpVO30VK0wTJ10Q9s

###Create a new user
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "email": "Ram@example.com",
  "password": "Hellloooo123",
  "name": "Ram Dutta"
}

###Get a user by id
GET http://localhost:3000/users/ed563b17-1a53-45fd-9831-4f3b73e95c82

###Sign in and copy accessToken into jwtToken above
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
  "email": "Ram@example.com",
  "password": "Hellloooo123"
}

###Who am I?
GET http://localhost:3000/auth/whoami
Authorization: Bearer {{jwtToken}}

###Get all users (admin only)
GET http://localhost:3000/users?email=Ram@example.com
Authorization: Bearer {{jwtToken}}

###Update user (admin only)
PATCH http://localhost:3000/users/ed563b17-1a53-45fd-9831-4f3b73e95c82
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
  "name": "Updated Name"
}

###Make user admin (admin only)
PATCH http://localhost:3000/users/ed563b17-1a53-45fd-9831-4f3b73e95c82/make-admin
Authorization: Bearer {{jwtToken}}

###Delete user (admin only)
DELETE http://localhost:3000/users/ed563b17-1a53-45fd-9831-4f3b73e95c82
Authorization: Bearer {{jwtToken}}

###Sign out
POST http://localhost:3000/auth/signout
