### Sign in first (same REST Client session)
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
  "email": "mohna1@example.com",
  "password": "Hello123"
}

### Get signed-in user posts
GET http://localhost:3000/posts/me

### Create Reaction (LIKE)

POST http://localhost:3000/reaction
Content-Type: application/json

{
"postId": "dd0a9d9d-1ee7-11f1-9aef-0a002700000e",
"type": "LIKE"
}

### Create Reaction (DISLIKE)

POST http://localhost:3000/reaction
Content-Type: application/json

{
"postId": "dd0a9d9d-1ee7-11f1-9aef-0a002700000e",
"type": "DISLIKE"
}

### Get Reaction Count for a Post

GET http://localhost:3000/reaction/dd0a9d9d-1ee7-11f1-9aef-0a002700000e

###  React to Another Post

POST http://localhost:3000/reaction
Content-Type: application/json

{
"postId": "dd0a94b7-1ee7-11f1-9aef-0a002700000e",
"type": "LIKE"
}

### Get Reaction Count for Another Post

GET http://localhost:3000/reaction/dd0a94b7-1ee7-11f1-9aef-0a002700000e

### Get Reaction Summary for All Posts
GET http://localhost:3000/reaction/posts
