@jwtToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlZDU2M2IxNy0xYTUzLTQ1ZmQtOTgzMS00ZjNiNzNlOTVjODIiLCJlbWFpbCI6IlJhbUBleGFtcGxlLmNvbSIsImFkbWluIjp0cnVlLCJpYXQiOjE3NzM3NTQ2OTYsImV4cCI6MTc3Mzg0MTA5Nn0.qNJDoFDJRJ9JOI0jMCW8Kgqa8uwH2n7Bnop9Zh2tCKc

### Sign in first and copy accessToken into jwtToken above
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
  "email": "Ram@example.com",
  "password": "Hellloooo123"
}

### Get signed-in user posts
GET http://localhost:3000/posts/me
Authorization: Bearer {{jwtToken}}

### Create Reaction (LIKE)

POST http://localhost:3000/reaction
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
"postId":"25bfe95c-ff9a-4def-b176-c6a2d6ea874d",
"type": "LIKE"
}

### Create Reaction (DISLIKE)

POST http://localhost:3000/reaction
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
"postId": "25bfe95c-ff9a-4def-b176-c6a2d6ea874d",
"type": "DISLIKE"
}

### Get Reaction Count for a Post

GET http://localhost:3000/reaction/dd0a9d9d-1ee7-11f1-9aef-0a002700000e

###  React to Another Post

POST http://localhost:3000/reaction
Content-Type: application/json
Authorization: Bearer {{jwtToken}}

{
"postId": "25bfe95c-ff9a-4def-b176-c6a2d6ea874d",
"type": "LIKE"
}

### Get Reaction Count for Another Post

GET http://localhost:3000/reaction/dd0a94b7-1ee7-11f1-9aef-0a002700000e

### Get Reaction Summary for All Posts
GET http://localhost:3000/reaction/posts
